### ISSUE TITLE
Most likely broken on Python<3.8

### ISSUE THREAD

**Issue by kwilcox** [conda-forge/kombu-feedstock#24]
@ocefpaf 

Upstream `kombu` added a requirement for the `importlib-metadata` backport in python versions less than 3.8: https://github.com/celery/kombu/blob/master/requirements/default.txt#L1

This is currently a `noarch` package and adding the `importlib-metadata` requirement with a filter of `python<3.8`  will remove that. Is there any downside to this?

The current `noarch` package in conda-forge is likely broken on py<3.8 due to this.

**Comment by ocefpaf** [comment]
> Is there any downside to this?

Removing noarch is fine in that cases. The downside is longer builds but with AzurePipelines that is not too bad these days. Just moved latest `kombu 4.6.7` to broken and I'll fix the recipe in a moment.

**Comment by kwilcox** [comment]
I'm guessing `noarch` packages only have the `tests` run for the python version that is doing the building (currently 3.8)? Is there a way to setup a matrix so a `noarch` package will test more than one python version?

**Comment by ocefpaf** [comment]
> I'm guessing `noarch` packages only have the `tests` run for the python version that is doing the building (currently 3.8)? Is there a way to setup a matrix so a `noarch` package will test more than one python version?

@jjhelmus was experimenting with that some time ago but I'm not sure what were the results (or if the effort is worth it).

**Comment by jjhelmus** [comment]
I though it was possible to test against multiple Python versions after the packages has been created using commands like:
```
conda build --test --python 2.7  /path/to/noarch/foo-1.0.0-py_0.tar.bz2
conda build --test --python 3.7  /path/to/noarch/foo-1.0.0-py_0.tar.bz2
```
But the `--python` argument looks to be ignored during the test phase.  Not sure if this was a change in conda-build or if I am remembering incorrectly.  Opening an issue in conda-build for this feature would be good. My limited search didn't find anything there already

**Comment by ocefpaf** [comment]
> Opening an issue in conda-build for this feature would be good. My limited search didn't find anything there already

Thanks @jjhelmus! I'll do that and ping some people who may contribute to it.
