### ISSUE TITLE
No Windows Packages for 4.6.8

### ISSUE THREAD

**Issue by alanhdu** [conda-forge/kombu-feedstock#30]
Looking at https://anaconda.org/conda-forge/kombu, it looks like the build for `4.6.8` have failed on Windows.

This is causing https://github.com/conda-forge/celery-feedstock/issues/35, in which `celery 4.4.1` cannot be installed on windows (because it relies on `kombu >= 4.6.8`.

It's not clear why this failed -- looking at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=127951&view=results, it looks like this might just be an intermittent failure? Can we just kick the and force the build to restart?

**Comment by igortg** [comment]
@conda-forge/core How is the standard procedure here? Should I open a PR with an empty commit to trigger a build?

**Comment by beckermr** [comment]
yep or even bump the build number

**Comment by alanhdu** [comment]
Filed #31 to bump up the build number
